//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace banhang
{
    using System;
    using System.Collections.Generic;
    
    public partial class ChiTietDonHang
    {
        public int id_chitietdonhang { get; set; }
        public Nullable<int> id_donhang { get; set; }
        public Nullable<int> id_sanpham { get; set; }
        public Nullable<int> so_luong { get; set; }
        public Nullable<decimal> gia { get; set; }
    
        public virtual DonHang DonHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}
